// Generated by CoffeeScript 2.5.1
(function() {
  // Create needed constants
  var bodyInput, form, list, submitBtn, titleInput;

  list = document.querySelector('ul');

  titleInput = document.querySelector('#title');

  bodyInput = document.querySelector('#body');

  form = document.querySelector('form');

  submitBtn = document.querySelector('form button');

}).call(this);
